name: Build core INDI Libs and Drivers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    strategy:
      fail-fast: false

    container:
      image: debian:trixie-slim

    steps:
      - name: Install git and dependencies
        run: |
          apt-get update
          apt-get install -qq -y git ca-certificates curl jq build-essential dpkg-dev git ca-certificates

      - name: Detect last release version
        run: |
          # Automatically detect the latest version from upstream releases
          UPSTREAM_TAG=$(curl -s https://api.github.com/repos/indilib/indi/releases/latest | jq -r .tag_name)
          VERSION=$(echo "$UPSTREAM_TAG" | sed 's/^v//')
          
          # Fallback error handling
          if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
            echo "Failed to fetch version from GitHub API. Using default version: 2.2.2"
            VERSION="2.2.2"
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Detected package version: $VERSION"
      
      - name: Get INDI Sources
        uses: actions/checkout@v6
        with:
          repository: 'indilib/indi'
          ref: refs/tags/v${{ env.VERSION }}
          path: 'indi'
      - name: Install build dependencies
        run: |
          apt-get build-dep -qqy ./indi
      - name: Build INDI Core Packages
        run: |
          indi/scripts/indi-core-deb.sh
      - name: Upload Compiled Debian Packages
        uses: actions/upload-artifact@v4
        with:
          # Nazwa, pod jaką artefakt będzie widoczny w zakładce Actions
          name: indi-compiled-packages
          # Ścieżka do plików. Wyszuka wszystkie pliki .deb w katalogu głównym 
          # oraz w podkatalogach (jeśli tam je przenosisz)
          path: |
            *.deb
            **/*.deb
          # Opcjonalnie: czas przechowywania w dniach (nadpisuje domyślne 90 dni)
          retention-days: 14
          # Gwarantuje, że błąd zapisu artefaktu przerwie potok i zasygnalizuje problem
          if-no-files-found: error
