name: kstars

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.architecture }}"]

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        architecture: ["arm64", "amd64"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.architecture }}

    steps:
      - name: Get KStars Sources
        run: |
          if [ -d kstars ]; then rm -rf kstars; fi
          git clone --depth 1 --branch stable-3.8.2 https://invent.kde.org/education/kstars.git

      - name: Install KStars Dependencies
        run: |
          dpkg -i build/libstellarsolver_*_${{ matrix.architecture }}.deb build/libstellarsolver-dev_*_${{ matrix.architecture }}.deb && \
          dpkg -i build/indi-bin_*_${{ matrix.architecture }}.deb build/libindi1_*_${{ matrix.architecture }}.deb build/libindi-data_*_all.deb build/libindi-dev_*_${{ matrix.architecture }}.deb && \
          dpkg -i build/indi-3rdparty-libs_*_${{ matrix.architecture }}.deb

      - name: Build Kstars Packages
        run: |
          rm -rf build/deb_kstars && mkdir -p build/deb_kstars && \
          cp -r kstars/* build/deb_kstars/ && \
          cp -r kstars/packaging/linux/debian build/deb_kstars/ && \
          cd build/deb_kstars && \
          sed -i "s/(6:3.8.2)/(6:3.8.2-1)/g" debian/changelog && \
          sed -i "s/knotifications5/knotifications6/g" debian/kstars-bleeding-data.install && \
          echo "export DEB_BUILD_OPTIONS := parallel=\$(shell nproc)" >> debian/rules && \
          sed -i "s/ kstars-bleeding-dbg (= \${binary:Version}),//g" debian/control && \
          fakeroot debian/rules binary
