name: indi-3rdparty-libs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.architecture }}"]

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        architecture: ["arm64", "amd64"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.architecture }}

    steps:
      - name: Get INDI 3rd Party Sources
        uses: actions/checkout@v6
        with:
          repository: 'indilib/indi-3rdparty'
          ref: refs/tags/v2.2.1.1
          path: 'indi-3rdparty'

      - name: Install INDI Core
        run: |
          dpkg -i build/indi-bin_*_${{ matrix.architecture }}.deb build/libindi1_*_${{ matrix.architecture }}.deb build/libindi-data_*_all.deb build/libindi-dev_*_${{ matrix.architecture }}.deb

      - name: Build INDI 3rd Party Libraries
        run: |
          mkdir -p build/deb_indi-3rdparty-libs && \
          cp -r indi-3rdparty/debian/indi-3rdparty-libs build/deb_indi-3rdparty-libs/debian && \
          cp -r indi-3rdparty/cmake_modules build/deb_indi-3rdparty-libs/ && \
          cp indi-3rdparty/CMakeLists.txt build/deb_indi-3rdparty-libs/ && \
          cp -r indi-3rdparty/lib* build/deb_indi-3rdparty-libs/ && \          
          cd build/deb_indi-3rdparty-libs && \
          fakeroot debian/rules binary
